env:
  node: true
  es2020: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  indent: ['error', 2],
  semi: 'off',
  no-trailing-spaces: ['warning'],
  no-console: ['error'],
  '@typescript-eslint/semi': ['error', 2]
}
