version: '3'
services:
  minio:
    image: minio/minio
    command: server /data
    ports:
      - "9000:9000"
    env_file:
      - ./.env
    volumes:
      - .:/data

  mc:
    image: minio/mc
    depends_on:
      - minio
    container_name: mcbkp
    env_file:
      - ./.env
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio http://minio:9000 $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY};
      /usr/bin/mc mc policy set public minio/pdtache
      "

  web:
    depends_on:
      - minio
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
