version: '3'
services:
  minio:
    image: minio/minio
    command: server /data
    ports:
      - "9000:9000"
    env_file:
      - ./docker.env
    volumes:
      - ./minio:/data

  mc:
    image: minio/mc
    depends_on:
      - minio
    env_file:
      - ./docker.env
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio http://localhost:9000 $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY};
      /usr/bin/mc mb minio/$${MINIO_ACCESS_KEY}$${MINIO_BUCKET} --ignore-existing;
      /usr/bin/mc policy set public minio/$${MINIO_BUCKET}
      "

  web:
    depends_on:
      - minio
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ./docker.env
